spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Backend_Springboot?serverTimezone=UTC
    username: root
    password: <<YOUR_PASSWORD>> # Cambia por tu contrase?a
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10

  # Configuraci?n de JPA e Hibernate
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        id:
          new_generator_mappings: true

  # Configuraci?n del servidor
server:
  port: 8080 # El backend corre en el puerto 8080

# Configuraci?n de JWT para autenticaci?n y autorizaci?n
jwt:
  secret: securesecretkey # Esta propiedad se utiliza, pero la clave segura se generar? en el c?digo.
  # Duraci?n del token en milisegundos (24 horas).

# Configuraci?n de CORS para permitir la comunicaci?n desde el frontend (puerto 8082)
# La configuraci?n de CORS se hace principalmente en el c?digo de configuraci?n de seguridad (SecurityConfig.java)

# Configuraci?n de manejo de errores
error:
  handling:
    http-status-in-json-response: true
    exception-logging: NO_LOGGING
    full-stacktrace-http-statuses: 5xx
    log-levels:
      5xx: ERROR


logging:
  level:
    root: INFO
    org.springframework: INFO
    org.hibernate.SQL: DEBUG
    com.myproyect.springboot: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"